'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { PasswordInput } from '@/components/ui/password-input';
import { useAuthStore } from '@/store/auth.store';
import axios from 'axios';
import { API_BASE_URL } from '@/lib/api';
import { Shield, Sparkles } from 'lucide-react';
import { CopyrightFooter } from '@/components/copyright-footer';

export default function LoginPage() {
  const router = useRouter();
  const { setAuth } = useAuthStore();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);

  // 2FA Challenge states
  const [is2faRequired, setIs2faRequired] = useState(false);
  const [tempToken, setTempToken] = useState('');
  const [otpCode, setOtpCode] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setSuccess(false);

    try {
      const response = await axios.post(`${API_BASE_URL}/auth/login`, {
        email,
        password,
      });

      if (response.data.is2faRequired) {
        setIs2faRequired(true);
        setTempToken(response.data.tempToken);
        return;
      }

      const { accessToken, refreshToken } = response.data;
      const payloadBase64 = accessToken.split('.')[1];
      const payload = JSON.parse(atob(payloadBase64));

      setAuth(accessToken, refreshToken, {
        id: payload.sub,
        email: payload.email,
        organization: payload.org || '',
        role: payload.role || '',
      });

      setSuccess(true);
      router.push('/');
    } catch (err: any) {
      console.error(err);
      setError(err.response?.data?.message || 'Login failed. Please check your credentials.');
    } finally {
      setLoading(false);
    }
  };

  const handle2faSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setSuccess(false);

    try {
      const response = await axios.post(`${API_BASE_URL}/auth/2fa/verify`, {
        tempToken,
        code: otpCode,
      });

      const { accessToken, refreshToken } = response.data;
      const payloadBase64 = accessToken.split('.')[1];
      const payload = JSON.parse(atob(payloadBase64));

      setAuth(accessToken, refreshToken, {
        id: payload.sub,
        email: payload.email,
        organization: payload.org || '',
        role: payload.role || '',
      });

      setSuccess(true);
      router.push('/');
    } catch (err: any) {
      console.error(err);
      setError(err.response?.data?.message || 'Invalid verification code.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="flex min-h-screen flex-col bg-[#0a0f1d] px-4 py-12 sm:px-6 lg:px-8">
      <div className="flex-1 flex items-center justify-center w-full">
        <div className="w-full max-w-md space-y-8 rounded-2xl border border-white/10 bg-white/5 p-8 backdrop-blur-md shadow-2xl animate-in fade-in zoom-in-95 duration-200">
          <div>
            <h2 className="mt-2 text-center text-3xl font-extrabold tracking-tight text-white flex items-center justify-center">
              {is2faRequired ? (
                <>
                  <Shield className="mr-2 h-7 w-7 text-cyan-400" />
                  Two-Factor Security
                </>
              ) : (
                <>
                  Sign in to <span className="bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent ml-1">ExpenseFlow AI</span>
                </>
              )}
            </h2>
            <p className="mt-2 text-center text-sm text-slate-400">
              {is2faRequired ? (
                'Enter the 6-digit TOTP code generated by your authenticator app.'
              ) : (
                <>
                  Or{' '}
                  <Link href="/signup" className="font-medium text-cyan-400 hover:text-cyan-300 transition-colors">
                    create a new organization
                  </Link>
                </>
              )}
            </p>
          </div>

          {error && (
            <div className="rounded-md bg-red-950/50 border border-red-500/30 p-4 text-sm text-red-400">
              {error}
            </div>
          )}

          {success && (
            <div className="rounded-md bg-emerald-950/50 border border-emerald-500/30 p-4 text-sm text-emerald-400">
              Successfully logged in! Redirecting...
            </div>
          )}

          {is2faRequired ? (
            /* 2FA Form */
            <form className="mt-8 space-y-6" onSubmit={handle2faSubmit}>
              <div>
                <label htmlFor="otp-code" className="block text-sm font-medium text-slate-300 mb-1">
                  Authenticator Code
                </label>
                <input
                  id="otp-code"
                  type="text"
                  required
                  maxLength={6}
                  value={otpCode}
                  onChange={(e) => setOtpCode(e.target.value.replace(/\D/g, ''))}
                  placeholder="123456"
                  className="flex h-12 w-full rounded-md border border-slate-700 bg-slate-900 px-3 py-2 text-center text-xl tracking-[0.75em] font-mono text-cyan-400 placeholder-slate-600 focus:border-cyan-500 focus:outline-none"
                />
              </div>

              <div className="flex items-center justify-between">
                <button
                  type="button"
                  onClick={() => {
                    setIs2faRequired(false);
                    setOtpCode('');
                    setError(null);
                  }}
                  className="text-xs text-slate-400 hover:text-white transition-colors"
                >
                  Back to credentials
                </button>
              </div>

              <div>
                <button
                  type="submit"
                  disabled={loading || otpCode.length !== 6}
                  className="group relative flex w-full justify-center rounded-md bg-gradient-to-r from-cyan-500 to-blue-600 py-2 px-4 text-sm font-medium text-white hover:from-cyan-400 hover:to-blue-500 focus:outline-none disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-300 transform hover:scale-[1.02] active:scale-[0.98]"
                >
                  {loading ? 'Verifying...' : 'Verify Code'}
                </button>
              </div>
            </form>
          ) : (
            /* Credentials Form */
            <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
              <div className="space-y-4 rounded-md">
                <div>
                  <label htmlFor="email-address" className="block text-sm font-medium text-slate-300 mb-1">
                    Email address
                  </label>
                  <input
                    id="email-address"
                    name="email"
                    type="email"
                    autoComplete="email"
                    required
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    className="flex h-10 w-full rounded-md border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-100 placeholder-slate-500 focus:border-cyan-500 focus:outline-none focus:ring-1 focus:ring-cyan-500"
                    placeholder="you@example.com"
                  />
                </div>

                <div>
                  <div className="flex items-center justify-between mb-1">
                    <label htmlFor="password" className="block text-sm font-medium text-slate-300">
                      Password
                    </label>
                    <Link href="/forgot-password" className="text-xs font-medium text-cyan-400 hover:text-cyan-300 transition-colors">
                      Forgot password?
                    </Link>
                  </div>
                  <PasswordInput
                    id="password"
                    name="password"
                    required
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    placeholder="••••••••"
                  />
                </div>
              </div>

              <div>
                <button
                  type="submit"
                  disabled={loading}
                  className="group relative flex w-full justify-center rounded-md bg-gradient-to-r from-cyan-500 to-blue-600 py-2 px-4 text-sm font-medium text-white hover:from-cyan-400 hover:to-blue-500 focus:outline-none disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-300 transform hover:scale-[1.02] active:scale-[0.98]"
                >
                  {loading ? 'Signing in...' : 'Sign in'}
                </button>
              </div>
            </form>
          )}
        </div>
      </div>
      <CopyrightFooter />
    </main>
  );
}
